// <auto-generated />
using System;
using Finance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.Web.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20250617154657_AdjustModels")]
    partial class AdjustModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finance.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Finance.Web.Models.Moviment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAppellant")
                        .HasColumnType("bit");

                    b.Property<DateTime>("movimentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("Moviments");

                    b.HasDiscriminator<int>("type").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Finance.Web.Models.Expense", b =>
                {
                    b.HasBaseType("Finance.Web.Models.Moviment");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Finance.Web.Models.Income", b =>
                {
                    b.HasBaseType("Finance.Web.Models.Moviment");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Finance.Web.Models.Moviment", b =>
                {
                    b.HasOne("Finance.Web.Models.Category", "Category")
                        .WithMany("Moviments")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Finance.Web.Models.Category", b =>
                {
                    b.Navigation("Moviments");
                });
#pragma warning restore 612, 618
        }
    }
}
